### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by bommbo** [coldnight/dump-brain-with-emacs#1]
您好，我想问您一下，这个关于org-mode中ein,那个是什么意思，我也想用emacs作笔记来的，参考了您的配置，但是我在babel中想添加一些其他的语言，我显示没有加载，所以想问下关于这个的配置。

**Comment by coldnight** [comment]
sorry，那是我的自己的配置拷贝有问题，ein 是在 Emacs 中使用 Jupyter Notebook，这个仓库 https://github.com/millejoh/emacs-ipython-notebook ，我修正一下。

**Comment by bommbo** [comment]
> sorry，那是我的自己的配置拷贝有问题，ein 是在 Emacs 中使用 Jupyter Notebook，这个仓库 https://github.com/millejoh/emacs-ipython-notebook ，我修正一下。

谢了，我找到问题原因了，javascript 和 cpp 语言的写法应该写成 js 和 C。

**Comment by coldnight** [comment]
好的，ein 也已经移除了。
